config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "boards#index"
  resources :boards do
    collection do
      get 'search'
    end
  end
  resources :comments, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :tags
  has_many :categories,through: :tags
  has_many :comments


  #validation
  validates :title, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tags
  has_many :boards,through: :tags
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :board
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :board
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!, only: [:new,:create]

  def index;@boards = Board.limit(5);end
  def new
    @board = Board.new;
    @categories = Category.all
  end

  def create
    @board = Board.new(board_params)
    @board.save
    redirect_to board_path @board
  end

  def show 
    @board = Board.find(params[:id])
  end

  def search
    # title
    @b = Board.where("title like ?","%#{search_params[:text]}%").ids
    # text
    @c =  Comment.where("text like ?","%#{search_params[:text]}%")
    @c.each do |c|
      @b << c.board_id #title and textをまとめる
    end
    @boards = Board.where(id: @b)
  end

  private
  def board_params
    params.require(:board).permit(:title,{category_ids: []})
  end

  def search_params
    params.require(:board).permit(:text)
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  def create
    @comment = Comment.new(text_params)
    @comment.save
    redirect_to board_path @comment.board_id
  end

  private

  def text_params
    params.require(:comment).permit(:text,:board_id).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/boards/index.html.erb
<div class="board_index">
<div class="top-content">
  <div class="top-left">
  ボード一覧
  </div>
  <div class="top-right">
    <a href= "<%= new_board_path %>">
    新規作成
    </a>
  </div>
</div>
<div class="main-content">

<% @boards.each do |b| %>
  <div class="main">
    <div class="board_image">
    </div>
    <div class="board_name">
      <%= link_to board_path(b.id) do%>
        <%= b.title %>
      <% end %>
    </div>
  </div>
<% end %>
</div>
</div>

app/views/boards/new.html.erb
<div class="board_index">
  <div class="top-content">
    <div class="top-left">
      <div class="title">
        新規投稿
      </div>
    </div>
    <div class="top-right">
    </div>
  </div>


<%= form_with(model: Board.new,local:true) do |f| %>
タイトル
  <%= f.text_field :title,placeholder: "タイトルを入力",required: true%>
  <br>
  <%= f.collection_check_boxes :category_ids,@categories,:id,:name,class: "category"%>
  <%= f.submit "投稿する",id: "submit"%>
<% end %>
</div>

app/views/boards/search.html.erb
検索結果
<%@boards.each do |b|%>
  <a href= "<%= board_path b.id %>">
  <br>
  <%= b.title %>
  </a>
<% end %>

app/views/boards/show.html.erb
<div class="board_index">
  <div class="top-content">
    <div class="top-left">
      <div class="title">
        <%= @board.title %>
      </div>
    </div>
    <div class="top-right">
      <a href= "<%= new_board_path %>">
        新規作成
      </a>
    </div>
  </div>

  <div class="category">
    <% @board.categories.each do |c| %>
      <div class="box">
        <%= c.name %>
      </div>
    <% end %>
  </div>

  <div class="show_content">
    <div class="main-content">
      <% @board.comments.each_with_index do |b,i| %>
        <div class="message">
          <div class="metadata">
            <span class="number"><%= i+1 %></span>
            <span class="name"><b>名無し</b></span><span class="date"><%= b.created_at %></span>
            <%= b.text %>
          </div>
        </div>
      <% end %>
    </div>

    <%= form_with(model: Comment.new, local: true,class: "show_form") do |f| %>
      <%= f.text_area :text,required: true,cols: 20,rows: 5 %>
      <%= f.hidden_field :board_id,value: @board.id %>
      <%= f.submit "投稿する" %>
    <% end %>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bbs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <div class="root">
    <%= link_to "TopPage", root_path %>
  </div>
  <div class="search">
    <%= form_with(model: Board.new,local:true,url: search_boards_path,method: :get, class: "form_w") do |f| %>
      <%= f.text_field :text,required:true %>
      <%= f.submit "検索する",id: "submit"%>
    <% end %>
  </div>
  <div class="devise">
   <%if user_signed_in? %>
      <%= link_to "ログアウト", destroy_user_session_path,method: :delete %>
    <% else %>
      <a href="<%= user_session_path%>">ログイン</a>
      <a href="<%= new_user_registration_path%>">新規登録</a>
    <% end %>
  </div>
  </header>
    <%= yield %>
  </body>
</html>